repos:
  - repo: local
    hooks:
      - id: blue
        name: blue
        entry: blue
        language: system
        types: [python]
        stages: [commit]
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [ python ]
        stages: [ commit ]